<Workspace Version="1.2.1.3083" X="-118.17661895227" Y="-545.125360099311" zoom="0.717032548317806" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="c972dcad-9fbd-482f-8bab-d2a74f15277b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1398.8653243884" y="994.874595630087" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit

clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *
import math

doc = DocumentManager.Instance.CurrentDBDocument

clr.ImportExtensions(Revit.GeometryConversion)

inn = [UnwrapElement(IN[0]),UnwrapElement(IN[1])]
conns = [0,1]

def disconnect(curve):
	connectors = curve.ConnectorManager.Connectors
	for conn in connectors:
		if conn.IsConnected:
			for c in conn.AllRefs:
				if conn.IsConnectedTo(c):
					conns[0] = conn
					conns[1] = c
					conn.DisconnectFrom(c)

angle = (IN[2]*math.pi)/180
TransactionManager.Instance.EnsureInTransaction(doc)


connectors = inn[0].MEPModel.ConnectorManager.Connectors
for c in connectors:
	if c.GetMEPConnectorInfo().IsPrimary:
		primary = c
		break
	primary = c
loc = inn[0].Location
ductloc = inn[1].Location
center = primary.CoordinateSystem.BasisZ
centerrot = XYZ(center.X,center.Y,center.Z)
line = Autodesk.Revit.DB.Line.CreateUnbound(primary.Origin,center)
disconnect(inn[1])
ductloc.Rotate(line,angle)
loc.Rotate(line,angle)
conns[0].ConnectTo(conns[1])

TransactionManager.Instance.TransactionTaskDone()

OUT =  IN[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="4d0c3860-94ce-4d93-9a6d-a07d9c3fa69d" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Pick Model Element" x="395.414395345851" y="1000.89421933093" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="True" />
      <ID value="9f550081-f503-4e21-b30d-71f41d410784" />
      <Name value="Pick Model Element" />
      <Description value="This offers a single selection of a model element. Created for Dynamo Player usage." />
      <Inputs>
        <Input value="refresh" />
      </Inputs>
      <Outputs>
        <Output value="element" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="d7cd0479-f57b-419f-b094-20d32c1ed1e3" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Pick Model Element" x="696.356963172947" y="1095.60536823046" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="True" />
      <ID value="9f550081-f503-4e21-b30d-71f41d410784" />
      <Name value="Pick Model Element" />
      <Description value="This offers a single selection of a model element. Created for Dynamo Player usage." />
      <Inputs>
        <Input value="refresh" />
      </Inputs>
      <Outputs>
        <Output value="element" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="41da1a56-f0bd-4d44-b030-dec0c39c8a4f" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Rhythm.TextBoxInput" x="900.830782440423" y="1298.78864616151" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="True" />
      <ID value="9bdc52e4-cb94-4c76-b423-832a895f6044" />
      <Name value="Rhythm.TextBoxInput" />
      <Description value="Provides a text box input for users. Allows for multiple strings if needed." />
      <Inputs>
        <Input value="reset" />
      </Inputs>
      <Outputs>
        <Output value="string" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c4f7c84e-a9e0-4de2-be73-32cd8718db63" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="String.ToNumber" x="1099.77799585571" y="1292.44531824037" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.String.ToNumber@string">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4d0c3860-94ce-4d93-9a6d-a07d9c3fa69d" start_index="0" end="c972dcad-9fbd-482f-8bab-d2a74f15277b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d7cd0479-f57b-419f-b094-20d32c1ed1e3" start_index="0" end="c972dcad-9fbd-482f-8bab-d2a74f15277b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="41da1a56-f0bd-4d44-b030-dec0c39c8a4f" start_index="0" end="c4f7c84e-a9e0-4de2-be73-32cd8718db63" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c4f7c84e-a9e0-4de2-be73-32cd8718db63" start_index="0" end="c972dcad-9fbd-482f-8bab-d2a74f15277b" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>